
server:
  port: 9095


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olif_management_system
    password:
    username: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
